services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_filta_test
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
    ports:
      - "8000:8000"
    networks:
      - filta_test_network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: filta_test_nginx
    restart: always
    tty: true
    ports:
      - "81:80"
      - 5173:5173
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - filta_test_network
  # MySQL Service
  db:
    image: mysql:8.0
    container_name: filta_test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: filta
      MYSQL_USER: filta_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - filta_test_network

  # PhpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    depends_on:
      - db
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8080:80"
    networks:
      - filta_test_network

volumes:
  db_data:

networks:
  filta_test_network:
    name: filta_test_network
    driver: bridge
